#!/usr/bin/env python3

import argparse
import anndata as ad
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scanpy as sc


def main(args):
    #########################
    ## MERGE ADATA OBJECTS ##
    #########################
    adatas = {}
    for file_path in args.adata_paths_input:
        adata = sc.read_h5ad(file_path)
        slide_id = adata.obs["slide"].unique()
        adatas[slide_id[0]] = adata

    merged_adata = ad.concat(adatas, index_unique="_", merge="same", uns_merge="unique")


    ##################
    ## ANNOTATE HVG ##
    ##################
    sc.pp.log1p(merged_adata)
    
    merged_adata.layers["counts"] = merged_adata.X.copy()
    sc.experimental.pp.highly_variable_genes(
        merged_adata,
        layer="counts",
        n_top_genes=args.n_top_genes,
        flavor="pearson_residuals",
        inplace=True,
        batch_key=args.batch_key,
    )
    full_features = merged_adata.var.copy()
    hvg_full = (
        merged_adata.var[merged_adata.var["highly_variable"]]
        .sort_values("highly_variable_rank")
        .head(3000)
        .index.tolist()
    )
    hvg_adata = merged_adata[:, merged_adata.var.index.isin(hvg_full)]
    hvg_features = hvg_adata.var.copy()

    sc.pl.highly_variable_genes(
        hvg_adata,
    )
    fig = plt.gcf()
    fig.suptitle(f"Highly variable genes dispersion plot - {args.output_prefix}", va="center", ha="center", fontsize=16)
    plt.savefig(f"{args.output_prefix}.hvg_dispersion.png", dpi=300, bbox_inches="tight")


    ##############################
    ## DIMENSIONALITY REDUCTION ##
    ##############################
    sc.pp.pca(
        hvg_adata,
        n_comps=args.n_comps,
        svd_solver="arpack",
    )

    # Save outputs
    metadata = merged_adata.obs
    metadata.to_csv(f"{args.output_prefix}.merged_metadata.csv")
    full_features.to_csv(f"{args.output_prefix}.all_genes.csv", index=True)
    hvg_features.to_csv(f"{args.output_prefix}.hvg_genes.csv", index=True)
    hvg_adata.write_h5ad(filename=args.adata_output, compression="gzip")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Merge adata objects and process to prepare for downstream analysis by identifying highly variable genes (HVGs) and PCA"
    )
    parser.add_argument(
        "-i",
        "--adata-paths-input",
        nargs="+",
        required=True,
        help="List of preprocessed adata objects to merge"
    )
    parser.add_argument(
        "-n",
        "--n-top-genes",
        type=int,
        required=True,
        help="Number of HVGs to keep using `scanpy.pp.highly_variable_genes` [3000]"
    )
    parser.add_argument(
        "-c",
        "--n-comps",
        type=int,
        required=True,
        help="Number of principal components to compute using `scanpy.pp.pca` [30]"
    )
    parser.add_argument(
        "-b",
        "--batch-key",
        type=str,
        required=True,
        help="Key in AnnData object for batch information ['batch_id']"
    )
    parser.add_argument(
        "-p",
        "--output-prefix",
        type=str,
        required=True,
        help="Output file name prefix for the HVGs plot and metadata (adata.obs) CSV"
    )
    parser.add_argument(
        "-o",
        "--adata-output",
        type=str,
        required=True,
        help="Output file name for the merged AnnData object"
    )

    args = parser.parse_args()

    main(args)
