#!/usr/bin/env python3

import argparse
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scanpy as sc
import squidpy as sq


def main(args):
    #############################################
    ## GENERATE ADATA OBJECT WITH SPATIAL DATA ##
    #############################################
    adata = sq.read.visium(
        path=args.spaceranger_spatial_dir,
        counts_file="filtered_feature_bc_matrix.h5",
        library_id=args.slide,
    )

    # Barcodes (or genes depending on Visium version) are the index for adata.var, if there are duplicates this will make it unique (e.g. TBCE vs. TBCE-1)
    adata.var_names_make_unique()

    # Add metadata
    adata.obs["team"] = args.team_id
    adata.obs["dataset"] = args.dataset_id
    adata.obs["sample"] = args.sample_id
    adata.obs["batch"] = args.batch
    adata.obs["batch_id"] = f"{args.team_id}_{args.dataset_id}_{args.batch}"
    adata.obs["visium_slide_ref"] = args.slide
    adata.obs["visium_capture_area"] = args.area
    
    # Save adata object
    adata.write_h5ad(filename=args.adata_output, compression="gzip")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Convert Space Ranger counts to adata objects"
    )
    parser.add_argument(
        "-t",
        "--team-id",
        type=str,
        required=True,
        help="Team ID"
    )
    parser.add_argument(
        "-d",
        "--dataset-id",
        type=str,
        required=True,
        help="Dataset ID"
    )
    parser.add_argument(
        "-s",
        "--sample-id",
        type=str,
        required=True,
        help="Sample ID"
    )
    parser.add_argument(
        "-b",
        "--batch",
        type=str,
        required=True,
        help="Batch from which the sample/dataset originated"
    )
    parser.add_argument(
        "-i",
        "--slide",
        type=str,
        required=True,
        help="The 10x Visium slide serial number"
    )
    parser.add_argument(
        "-a",
        "--area",
        type=str,
        required=True,
        help="The 10x Visium slide capture area"
    )
    parser.add_argument(
        "-f",
        "--spaceranger-spatial-dir",
        type=str,
        required=True,
        help="Spaceranger spatial outputs directory/folder"
    )
    parser.add_argument(
        "-o",
        "--adata-output",
        type=str,
        required=True,
        help="Output file name for the AnnData object"
    )

    args = parser.parse_args()

    main(args)
